name: Docker Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual trigger

env:
  REGISTRY: docker.io
  IMAGE_NAME: malithrukshan/thumb-gen

jobs:
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get release version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            # Extract version from release tag (remove 'v' prefix if present)
            VERSION=${{ github.event.release.tag_name }}
            VERSION=${VERSION#v}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "Release version: ${VERSION}"
          else
            # For manual triggers, use a default or get from package.json
            echo "version=manual-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.version.outputs.version }}
      
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: >-
            🎨 Free online thumbnail generator for videos, Lottie animations, images, and text. 
            No signup required, fully client-side processing!
          readme-filepath: ./README.md